PPW_First_Wave_Assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf.urls import handler404
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(permanent=True, url='/dashboard/'), name='dashboard'),
    path('dashboard/', include('dashboard.urls')),
    path('donation_form/', include('donation_form.urls')),
    path('register/', include('register.urls')),
    path('news/', include('news.urls')),
    path('about/', include('about.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},name='logout'),
    path('profile/', include('profil.urls')),
]

handler404 = 'main.views.page_not_found'

news/urls.py
from django.urls import path
from news.views import news, detailnews

app_name = 'news'

urlpatterns = [
    path('', news, name = 'news'),
    path('detail/<int:pk>/', detailnews, name = 'detailnews'),
]

profil/urls.py
from django.urls import path
from profil.views import *

app_name = 'profil'
urlpatterns = [
	path('', profil, name = 'profil'),
    path('cek-history/', cek_history, name='cek-history'),
]

templates/partials/footer.html
<div class="bg-primary text-white px-3 py-3">
    <p class="float-right text-white"><a href="#" class="text-white">Back to top</a></p>
    <p>© 2017-2018 PPW Survivor, Inc.</p>
    <p>The best among you are those who bring greatest benefits to many others.</p>
</nav>

templates/partials/header.html
<nav class="sticky-top navbar navbar-expand-sm navbar-light bg-primary">
    <a class="navbar-brand text-white">KumpulDonasi</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav ml-auto mr-2">
            <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'dashboard' %}">Beranda</a>
            </li>
            <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'news:news' %}">Berita</a>
            </li>
            <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'donation_form' %}">Donasi</a>
            </li>
            <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'about' %}">About</a>
            </li>
        </ul>
        <a class="nav-link text-white disable" href="">|</a>
        {% if user.is_authenticated %}    
            <a class="nav-link text-white" href="{% url 'profil:profil' %}">Hello, {{user}}!</a>
            <a class="btn btn-outline-light" href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a class="btn btn-outline-light" href="{% url 'social:begin' 'google-oauth2' %}">Login</a>
        {% endif %}
    </div>
</nav>