PPW_First_Wave_Assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf.urls import handler404
from django.views.generic import RedirectView
from django.contrib.auth.views import LogoutView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(permanent=True, url='/dashboard/'), name='dashboard'),
    path('dashboard/', include('dashboard.urls')),
    path('donation_form/', include('donation_form.urls')),
    path('register/', include('register.urls')),
    path('news/', include('news.urls')),
    path('about/', include('about.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},name='logout'),
    path('profile/', include('profil.urls')),
]

handler404 = 'main.views.page_not_found'

dashboard/urls.py
from django.urls import path
from dashboard.views import *

app_name = 'dashboard'
urlpatterns = [
	path('detail/<int:pk>/', detail, name = 'detail'),
    path('', dashboard, name = 'dashboard'),
]

news/urls.py
from django.urls import path
from news.views import news, detailnews

app_name = 'news'

urlpatterns = [
    path('', news, name = 'news'),
    path('detail/<int:pk>/', detailnews, name = 'detailnews'),
]

news/models.py
from django.db import models
from main.models import Program

# Create your models here.

news/views.py
from django.shortcuts import render
from main.models import News

def news(request):
	news_data_all = News.objects.all()[:]
	return render(request, 'news.html', {'news_data_all':news_data_all})

def detailnews(request,pk):
	news_data = News.objects.get(pk=pk)
	return render(request, 'detailnews.html', {'news_data':news_data})

news/templates/detailnews.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
	
		<div style="text-align: center;">
			<img src="{{ data.photo }}">
		</div>

		<div class="container-fluid">
			<div class="border border-0 card m-4">
				<div class="card-body bg-primary">
					<h2 class="text-left text-white">{{ news_data.news_name }}</h2>
					<p>{{ news_data.description }}</p>
				</div>
			</div>
		</div>

		<div class="container-fluid">
			<div class="border border-0 card">
				<div class="card-body bg-secondary">
					<h2 class="text-center text-light">Daftar Program Donasi</h2>
				</div>
			</div>
		</div>

		{% for data in news_data.program.all %}
    		<div class="container-fluid">
	    		<div class="border border-0 card m-2">
		    		<div class="card-body bg-light">
		    			<div class="row">
		    				<div class ="col-sm-4">
			    				<img class="img-fluid text-left" src="{{ data.photo }}">
			    			</div>

			    			<div class="col-sm-8">
			    				<a href="{% url 'dashboard:detail' data.pk %}">
			    					<h2 class="text-justify">{{data.program_name}}</h2> 	
			    				</a>
			    				
			    				<p>{{ data.summary}}</p>
			    				
			    				<br>
			    				<div class="row mt-1">
			    					<div class="col-sm">
			    						<div class="border-0 card bg-white">
			    							<article class="text-center">
			    								Donasi Terkumpul :
			    							</article>
			    							<article class="text-center">
			    								{{ data.get_all_donation }}
			    							</article>
			    						</div>
			    					</div>

			    					<div class="col-sm ">
			    						<a href="/donation_form/">
			    							<button class="border-0 card btn-block bg-warning btn-lg">
				    						<!-- 	<span class="text-center align-middle"> -->
													Salurkan Donasi
												<!-- </span> -->
				    						</button>
			    						</a>
			    						
			    					</div>
			    				</div>
			    			</div>
		    			</div>    			
		    		</div>
		    	</div>
	    	</div>
    	{% endfor %}

	
{% endblock %}

news/templates/news.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
	{% if news_data_all %}
		<div class="container-fluid">
			<div class="row">
				{% for data in news_data_all %}
				<div class="col-lg-6">
					<div class="border border-0 card m-4">
						<div class="card-body bg-light">
							<a href="{% url 'news:detailnews' data.pk %}">
			    				<h2 class="text-justify">{{ data.news_name }}</h2>
			    			</a>
							<div class="row">
								<div class ="col-sm-6">
									<img class="img-fluid text-left" src="{{ data.photo }}">
								</div>

								<div class="col-sm-6">
									<p>{{ data.summary }}</p>
									<a href="{% url 'news:detailnews' data.pk %}">
										<article class="text-right">Selengkapnya ></article>
									</a>
								</div>
							</div>       
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	{% else %}
		<br>
		<h1 class="text-main" style="text-align: center;">--Tidak Ada Berita--</h1>
	{% endif %}
{% endblock %}